name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository_owner == krshoss
    name: Release Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: Krish Gupta
          GIT_AUTHOR_EMAIL: krshg@outlook.com
          GIT_COMMITTER_NAME: Krish Gupta
          GIT_COMMITTER_EMAIL: krshg@outlook.com
